In [1]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))

In [9]:
print(sigmoid(-1))

0.2689414213699951


In [30]:
def np_sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [31]:
np_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [32]:
print(np_sigmoid(x))

[0.73105858 0.88079708 0.95257413]


In [33]:
def gradient(x):
    return np_sigmoid(x)*(1-np_sigmoid(x))
gradient(x)

array([0.19661193, 0.10499359, 0.04517666])

In [54]:
def reshape_img(img):
    print(img)
    new_image=img.reshape(img.shape[0]*img.shape[1]*img.shape[2],1)
    print(len(new_image))
    return img.reshape(img.shape[0]*img.shape[1]*img.shape[2],1)

In [55]:
image=np.array([[[0.4235223, 0.52335345],
                    [0.5325235, 0.52353235],
                    [0.5453453, 0.54334634]],

                   [[0.4235223, 0.52335345],
                    [0.5325235, 0.52353235],
                    [0.5453453, 0.54334634]],

                   [[0.4235223, 0.52335345],
                    [0.5325235, 0.52353235],
                    [0.5453453, 0.54334634]]])

In [52]:
print(image.shape[0])

3


In [56]:
print(reshape_img(image))

[[[0.4235223  0.52335345]
  [0.5325235  0.52353235]
  [0.5453453  0.54334634]]

 [[0.4235223  0.52335345]
  [0.5325235  0.52353235]
  [0.5453453  0.54334634]]

 [[0.4235223  0.52335345]
  [0.5325235  0.52353235]
  [0.5453453  0.54334634]]]
18
[[0.4235223 ]
 [0.52335345]
 [0.5325235 ]
 [0.52353235]
 [0.5453453 ]
 [0.54334634]
 [0.4235223 ]
 [0.52335345]
 [0.5325235 ]
 [0.52353235]
 [0.5453453 ]
 [0.54334634]
 [0.4235223 ]
 [0.52335345]
 [0.5325235 ]
 [0.52353235]
 [0.5453453 ]
 [0.54334634]]


In [69]:
def normalised(x):
    norm=np.linalg.norm(x,axis=1,keepdims=True)
    return x/norm

In [73]:
img=np.array([[0,100,4],[2,6,4]])
print(normalised(img))

[[0.         0.99920096 0.03996804]
 [0.26726124 0.80178373 0.53452248]]


In [74]:
def softmax(x):
    x=np.exp(x)
    norm=np.linalg.norm(x,axis=1,keepdims=True)
    return x/norm

In [82]:
x=[[9,2,5,0,0],
   [7,5,0,0,0]]

In [83]:
print(softmax(x))

[[9.99831880e-01 9.11728660e-04 1.83125597e-02 1.23389056e-04
  1.23389056e-04]
 [9.90964875e-01 1.34112512e-01 9.03642998e-04 9.03642998e-04
  9.03642998e-04]]


In [94]:
import time

In [113]:
x=[1,5,3,2,3,4,5,3,2,3,5,2,4,5,32,53,2,34,2,35,2,5,234,53]
y=[2,1,3,5,2,4,3,5,2,4,2,4,5,4,345,543,24,54,64,23,5,4,5,3]

start_time=time.process_time()
dot=0
for i in range(len(x)):
    dot+=x[i]*y[i]
end_time=time.process_time()
elapsed_time_ms = 1000 * (end_time - start_time)

print(f"Dot Product {dot} : Process Time {elapsed_time_ms:.7f} ms")


x=np.array([1,5,3,2,3,4,5,3,2,3,5,2,4,5,32,53,2,34,2,35,2,5,234,53])
y=np.array([2,1,3,5,2,4,3,5,2,4,2,4,5,4,345,543,24,54,64,23,5,4,5,3])
tic=time.process_time()
dot=np.dot(x,y)
toc=time.process_time()
time_taken=1000*(toc-tic)
print(f"Dot {dot} : Process Time {time_taken:.7f} ms")


Dot Product 44147 : Process Time 0.0000000 ms
Dot 44147 : Process Time 0.0000000 ms
